In [79]:
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import RNN, Embedding, TextVectorization, StringLookup, GRU, LSTM, Dense

In [62]:
import tensorflow_datasets as tfds

In [63]:
import numpy as np

In [64]:
text = np.array(['+', 'sin', 'x1']).reshape(-1, 1)
tokens = np.unique(text)

In [67]:
vectorizer = StringLookup(vocabulary=tokens)

In [70]:
vectorizer(text)

<tf.Tensor: shape=(3, 1), dtype=int64, numpy=
array([[1],
       [2],
       [3]])>

In [73]:
embedder = Embedding(input_dim=len(vectorizer.get_vocabulary()), output_dim=12)

In [74]:
embedder(vectorizer(text))

<tf.Tensor: shape=(3, 1, 12), dtype=float32, numpy=
array([[[ 0.01618708,  0.03799445,  0.03580436, -0.02481052,
         -0.01137507, -0.00139005, -0.02348791,  0.02803003,
          0.03311243,  0.03612817, -0.04940659, -0.04298007]],

       [[-0.02084932,  0.04141309,  0.00839714, -0.00213595,
          0.0416964 , -0.03119251, -0.03070717, -0.02268248,
          0.04693622, -0.0035063 , -0.01526749, -0.01106911]],

       [[ 0.03122333,  0.01605279, -0.04318184,  0.01081733,
         -0.03812277,  0.01569569,  0.02369802,  0.03902237,
          0.0456183 ,  0.02502738,  0.02696556,  0.02938186]]],
      dtype=float32)>

In [77]:
recurrent_layer = LSTM(128)

In [78]:
recurrent_layer(embedder(vectorizer(text)))

<tf.Tensor: shape=(3, 128), dtype=float32, numpy=
array([[ 6.93470822e-04, -1.90159350e-04,  4.39327327e-04,
        -3.21497500e-04,  1.18867916e-04,  2.80930166e-04,
        -2.52402900e-03,  3.32903786e-04,  1.21357967e-03,
         4.00167570e-04, -1.97768110e-04,  3.87896178e-03,
        -2.12886441e-03, -3.02895135e-03,  4.45594720e-04,
        -1.25765248e-04,  4.80319693e-04,  1.12742197e-03,
        -3.09784315e-04, -2.09125015e-03, -9.44129599e-04,
        -3.34864110e-03,  1.13232224e-03, -2.50123674e-03,
         3.35686462e-04, -2.43262411e-03,  7.89508456e-04,
         1.54266204e-03, -1.70091703e-03, -2.03297846e-03,
         5.69938391e-04, -8.73219222e-04,  4.81547409e-04,
        -8.54747079e-04,  2.02862103e-03,  3.03674792e-03,
        -1.49211090e-03,  1.31301896e-03, -3.82388302e-04,
        -1.23970304e-03, -3.53792799e-03,  2.13692477e-03,
         1.61459879e-03, -1.31748588e-04,  9.32225201e-04,
         1.26020040e-03,  2.17198263e-04,  3.40529135e-04,
      

In [82]:
dense = Dense(len(tokens), activation='softmax')

In [83]:
dense(recurrent_layer(embedder(vectorizer(text))))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.33362806, 0.33380574, 0.33256626],
       [0.33340862, 0.33412963, 0.33246168],
       [0.3331486 , 0.33289936, 0.33395207]], dtype=float32)>