In [1]:
import sys
from typing import Literal

import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import GRU, Dense, Embedding, SimpleRNN, StringLookup
from tensorflow.keras.models import Model

%load_ext autoreload
%autoreload 2

sys.path.append("../")
from equation_discover import *

2023-12-03 18:53:33.647553: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-03 18:53:33.653851: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-03 18:53:33.685803: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-03 18:53:33.685831: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-03 18:53:33.686762: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to

In [3]:
n_samples = 32
sampler = EquationSampler(BASE_TOKENS, 16, 2)
(
    sequences,
    entropies,
    log_probs,
    counters,
    lengths,
    sequence_mask,
) = sampler.sample_sequence(n_samples, repeat=1)

In [19]:
sequences = TensorExpress(sequences)

In [20]:
sequences.astype(tf.int32)

<tf.Tensor: shape=(32, 1), dtype=int32, numpy=
array([[7],
       [2],
       [1],
       [4],
       [4],
       [7],
       [2],
       [2],
       [7],
       [2],
       [0],
       [3],
       [7],
       [4],
       [6],
       [4],
       [2],
       [1],
       [2],
       [2],
       [2],
       [2],
       [4],
       [2],
       [7],
       [7],
       [0],
       [7],
       [4],
       [2],
       [7],
       [7]], dtype=int32)>

In [14]:
tf.cast(sequences, dtype=tf.float32)

<tf.Tensor: shape=(32, 1), dtype=float32, numpy=
array([[7.],
       [2.],
       [1.],
       [4.],
       [4.],
       [7.],
       [2.],
       [2.],
       [7.],
       [2.],
       [0.],
       [3.],
       [7.],
       [4.],
       [6.],
       [4.],
       [2.],
       [1.],
       [2.],
       [2.],
       [2.],
       [2.],
       [4.],
       [2.],
       [7.],
       [7.],
       [0.],
       [7.],
       [4.],
       [2.],
       [7.],
       [7.]], dtype=float32)>

In [7]:
tf.reduce_any(tf.reduce_all(sequence_mask, axis=1))

<tf.Tensor: shape=(), dtype=bool, numpy=True>