In [1]:
import sys
from collections import namedtuple

import numpy as np
import tensorflow as tf

sys.path.append("../")
from equation_discover import *

2023-12-29 14:41:26.597552: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [14]:
tuple([init_state])

(LoopState(i=0, x=<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[-1.271224  ],
        [ 1.5117149 ],
        [-1.8407729 ],
        [ 0.5429096 ],
        [ 0.54613304],
        [ 0.43408063],
        [-0.76557887],
        [ 0.59539694],
        [-0.14712419],
        [-0.42406607]], dtype=float32)>, y=<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[ 1.5121831 ],
        [ 1.0233103 ],
        [-0.5891249 ],
        [ 0.822286  ],
        [-0.13375574],
        [ 0.7741584 ],
        [ 1.8876705 ],
        [-1.2288393 ],
        [ 1.058822  ],
        [-0.5765435 ]], dtype=float32)>),)

In [2]:
LoopState = namedtuple("LoopState", "i, x, y")

init_state = LoopState(
    0,
    tf.random.normal((10, 1)),
    tf.random.normal((10, 1)),
)

2023-12-29 14:41:28.844742: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [7]:
def body(state: LoopState):
    return (
        LoopState(
            state.i + 1,
            tf_append(state.x, tf.random.normal((10,))),
            tf_append(state.x, tf.random.normal((10,))),
        ),
    )


def cond(state: LoopState):
    return state.i < 10

In [8]:
tf.while_loop(cond, body, loop_vars=(init_state,))

(LoopState(i=<tf.Tensor: shape=(), dtype=int32, numpy=10>, x=<tf.Tensor: shape=(10, 11), dtype=float32, numpy=
 array([[-1.271224  , -1.7248333 , -1.0838443 ,  0.06722423, -1.6213256 ,
          1.0987594 , -0.10312328, -0.10186192,  0.06087451, -0.13325644,
         -0.6784275 ],
        [ 1.5117149 ,  0.5843664 , -0.8197026 , -1.1790277 , -0.3847549 ,
         -0.8276474 ,  1.0528581 , -1.1476573 ,  1.5670059 , -0.37416834,
          1.2312888 ],
        [-1.8407729 ,  0.3471497 ,  0.30440506,  0.4035066 ,  0.35188517,
          0.04602135,  0.68043536,  0.870286  ,  0.75525373,  0.05831465,
         -1.0230006 ],
        [ 0.5429096 ,  0.45549244,  0.01190468, -0.19186549, -1.1351526 ,
         -0.04225135, -0.0227738 ,  0.25598702, -0.43833923,  0.11107502,
          0.03640267],
        [ 0.54613304, -0.74188685, -0.3809284 , -1.0721188 ,  1.4731231 ,
          0.9472128 , -0.6455396 ,  0.01162487,  0.94817024, -0.68581957,
          1.453261  ],
        [ 0.43408063, -0.6282073 ,