In [20]:
import tensorflow as tf
import tensorflow_probability as tfp
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [65]:
@tf.custom_gradient
def log1pexp(x, y):
    print(x, y)
    def grad(dx):
        print(dx)
        return dx, dx
    return tf.math.log(1 + tf.exp(x)) + y, grad

In [70]:
inputs = tf.Variable(tf.random.normal((10, 3)))

In [71]:
model = Sequential()
model.add(Dense(10, activation='tanh'))
model.add(Dense(1))

In [72]:
output = model(inputs)
output = log1pexp(output, inputs)

tf.Tensor(
[[-0.21937865]
 [ 0.3833718 ]
 [ 0.17572612]
 [-0.18281412]
 [-0.64820266]
 [ 0.9988092 ]
 [-0.40058273]
 [-0.33761802]
 [-0.84231997]
 [ 0.0018563 ]], shape=(10, 1), dtype=float32) <tf.Variable 'Variable:0' shape=(10, 3) dtype=float32, numpy=
array([[ 1.356125  , -0.11717035,  0.50555605],
       [-1.0610327 ,  0.3639876 , -1.2643489 ],
       [ 1.3608096 , -0.60662085, -0.16662632],
       [ 1.5683467 , -0.2632117 ,  0.5779308 ],
       [-0.4747596 ,  0.12315901,  1.2562274 ],
       [-0.71512324, -1.4497582 , -2.148402  ],
       [-1.3453369 , -0.0447057 ,  1.633077  ],
       [-0.4098914 ,  1.1970062 , -0.7390156 ],
       [ 0.20384552,  1.3272736 ,  0.83290625],
       [-1.3316056 ,  0.34405234, -0.01651139]], dtype=float32)>


In [73]:
with tf.GradientTape() as tape:
    output = model(inputs)
    output = log1pexp(output, inputs)
tape.gradient(output, inputs)

tf.Tensor(
[[-0.21937865]
 [ 0.3833718 ]
 [ 0.17572612]
 [-0.18281412]
 [-0.64820266]
 [ 0.9988092 ]
 [-0.40058273]
 [-0.33761802]
 [-0.84231997]
 [ 0.0018563 ]], shape=(10, 1), dtype=float32) <tf.Variable 'Variable:0' shape=(10, 3) dtype=float32, numpy=
array([[ 1.356125  , -0.11717035,  0.50555605],
       [-1.0610327 ,  0.3639876 , -1.2643489 ],
       [ 1.3608096 , -0.60662085, -0.16662632],
       [ 1.5683467 , -0.2632117 ,  0.5779308 ],
       [-0.4747596 ,  0.12315901,  1.2562274 ],
       [-0.71512324, -1.4497582 , -2.148402  ],
       [-1.3453369 , -0.0447057 ,  1.633077  ],
       [-0.4098914 ,  1.1970062 , -0.7390156 ],
       [ 0.20384552,  1.3272736 ,  0.83290625],
       [-1.3316056 ,  0.34405234, -0.01651139]], dtype=float32)>
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(10, 3), dtype=float32)


InvalidArgumentError: {{function_node __wrapped____MklMatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [10,3], In[1]: [10,1] [Op:MatMul]